// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/BKWalFormats.proto

package org.apache.hadoop.hbase.regionserver.wal.bk;

public final class BKWalFormats {
  private BKWalFormats() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RegionLogOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 seqNum = 1;
    boolean hasSeqNum();
    long getSeqNum();
    
    // optional int64 ledgerId = 2;
    boolean hasLedgerId();
    long getLedgerId();
  }
  public static final class RegionLog extends
      com.google.protobuf.GeneratedMessage
      implements RegionLogOrBuilder {
    // Use RegionLog.newBuilder() to construct.
    private RegionLog(Builder builder) {
      super(builder);
    }
    private RegionLog(boolean noInit) {}
    
    private static final RegionLog defaultInstance;
    public static RegionLog getDefaultInstance() {
      return defaultInstance;
    }
    
    public RegionLog getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.internal_static_RegionLog_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.internal_static_RegionLog_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 seqNum = 1;
    public static final int SEQNUM_FIELD_NUMBER = 1;
    private long seqNum_;
    public boolean hasSeqNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getSeqNum() {
      return seqNum_;
    }
    
    // optional int64 ledgerId = 2;
    public static final int LEDGERID_FIELD_NUMBER = 2;
    private long ledgerId_;
    public boolean hasLedgerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getLedgerId() {
      return ledgerId_;
    }
    
    private void initFields() {
      seqNum_ = 0L;
      ledgerId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, seqNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, ledgerId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, seqNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, ledgerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.internal_static_RegionLog_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.internal_static_RegionLog_fieldAccessorTable;
      }
      
      // Construct using org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        seqNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        ledgerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.getDescriptor();
      }
      
      public org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog getDefaultInstanceForType() {
        return org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.getDefaultInstance();
      }
      
      public org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog build() {
        org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog buildPartial() {
        org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog result = new org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.seqNum_ = seqNum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ledgerId_ = ledgerId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog) {
          return mergeFrom((org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog other) {
        if (other == org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.getDefaultInstance()) return this;
        if (other.hasSeqNum()) {
          setSeqNum(other.getSeqNum());
        }
        if (other.hasLedgerId()) {
          setLedgerId(other.getLedgerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              seqNum_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ledgerId_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 seqNum = 1;
      private long seqNum_ ;
      public boolean hasSeqNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getSeqNum() {
        return seqNum_;
      }
      public Builder setSeqNum(long value) {
        bitField0_ |= 0x00000001;
        seqNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearSeqNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        seqNum_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 ledgerId = 2;
      private long ledgerId_ ;
      public boolean hasLedgerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getLedgerId() {
        return ledgerId_;
      }
      public Builder setLedgerId(long value) {
        bitField0_ |= 0x00000002;
        ledgerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearLedgerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ledgerId_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:RegionLog)
    }
    
    static {
      defaultInstance = new RegionLog(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RegionLog)
  }
  
  public interface RegionLogsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .RegionLog log = 1;
    java.util.List<org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog> 
        getLogList();
    org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog getLog(int index);
    int getLogCount();
    java.util.List<? extends org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogOrBuilder> 
        getLogOrBuilderList();
    org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogOrBuilder getLogOrBuilder(
        int index);
  }
  public static final class RegionLogs extends
      com.google.protobuf.GeneratedMessage
      implements RegionLogsOrBuilder {
    // Use RegionLogs.newBuilder() to construct.
    private RegionLogs(Builder builder) {
      super(builder);
    }
    private RegionLogs(boolean noInit) {}
    
    private static final RegionLogs defaultInstance;
    public static RegionLogs getDefaultInstance() {
      return defaultInstance;
    }
    
    public RegionLogs getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.internal_static_RegionLogs_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.internal_static_RegionLogs_fieldAccessorTable;
    }
    
    // repeated .RegionLog log = 1;
    public static final int LOG_FIELD_NUMBER = 1;
    private java.util.List<org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog> log_;
    public java.util.List<org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog> getLogList() {
      return log_;
    }
    public java.util.List<? extends org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogOrBuilder> 
        getLogOrBuilderList() {
      return log_;
    }
    public int getLogCount() {
      return log_.size();
    }
    public org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog getLog(int index) {
      return log_.get(index);
    }
    public org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogOrBuilder getLogOrBuilder(
        int index) {
      return log_.get(index);
    }
    
    private void initFields() {
      log_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < log_.size(); i++) {
        output.writeMessage(1, log_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < log_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, log_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.internal_static_RegionLogs_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.internal_static_RegionLogs_fieldAccessorTable;
      }
      
      // Construct using org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLogFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (logBuilder_ == null) {
          log_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          logBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs.getDescriptor();
      }
      
      public org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs getDefaultInstanceForType() {
        return org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs.getDefaultInstance();
      }
      
      public org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs build() {
        org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs buildPartial() {
        org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs result = new org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs(this);
        int from_bitField0_ = bitField0_;
        if (logBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            log_ = java.util.Collections.unmodifiableList(log_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.log_ = log_;
        } else {
          result.log_ = logBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs) {
          return mergeFrom((org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs other) {
        if (other == org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs.getDefaultInstance()) return this;
        if (logBuilder_ == null) {
          if (!other.log_.isEmpty()) {
            if (log_.isEmpty()) {
              log_ = other.log_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLogIsMutable();
              log_.addAll(other.log_);
            }
            onChanged();
          }
        } else {
          if (!other.log_.isEmpty()) {
            if (logBuilder_.isEmpty()) {
              logBuilder_.dispose();
              logBuilder_ = null;
              log_ = other.log_;
              bitField0_ = (bitField0_ & ~0x00000001);
              logBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLogFieldBuilder() : null;
            } else {
              logBuilder_.addAllMessages(other.log_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.Builder subBuilder = org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addLog(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .RegionLog log = 1;
      private java.util.List<org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog> log_ =
        java.util.Collections.emptyList();
      private void ensureLogIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          log_ = new java.util.ArrayList<org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog>(log_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog, org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.Builder, org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogOrBuilder> logBuilder_;
      
      public java.util.List<org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog> getLogList() {
        if (logBuilder_ == null) {
          return java.util.Collections.unmodifiableList(log_);
        } else {
          return logBuilder_.getMessageList();
        }
      }
      public int getLogCount() {
        if (logBuilder_ == null) {
          return log_.size();
        } else {
          return logBuilder_.getCount();
        }
      }
      public org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog getLog(int index) {
        if (logBuilder_ == null) {
          return log_.get(index);
        } else {
          return logBuilder_.getMessage(index);
        }
      }
      public Builder setLog(
          int index, org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog value) {
        if (logBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogIsMutable();
          log_.set(index, value);
          onChanged();
        } else {
          logBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setLog(
          int index, org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.Builder builderForValue) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          log_.set(index, builderForValue.build());
          onChanged();
        } else {
          logBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addLog(org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog value) {
        if (logBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogIsMutable();
          log_.add(value);
          onChanged();
        } else {
          logBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addLog(
          int index, org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog value) {
        if (logBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogIsMutable();
          log_.add(index, value);
          onChanged();
        } else {
          logBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addLog(
          org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.Builder builderForValue) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          log_.add(builderForValue.build());
          onChanged();
        } else {
          logBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addLog(
          int index, org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.Builder builderForValue) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          log_.add(index, builderForValue.build());
          onChanged();
        } else {
          logBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllLog(
          java.lang.Iterable<? extends org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog> values) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          super.addAll(values, log_);
          onChanged();
        } else {
          logBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearLog() {
        if (logBuilder_ == null) {
          log_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          logBuilder_.clear();
        }
        return this;
      }
      public Builder removeLog(int index) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          log_.remove(index);
          onChanged();
        } else {
          logBuilder_.remove(index);
        }
        return this;
      }
      public org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.Builder getLogBuilder(
          int index) {
        return getLogFieldBuilder().getBuilder(index);
      }
      public org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogOrBuilder getLogOrBuilder(
          int index) {
        if (logBuilder_ == null) {
          return log_.get(index);  } else {
          return logBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogOrBuilder> 
           getLogOrBuilderList() {
        if (logBuilder_ != null) {
          return logBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(log_);
        }
      }
      public org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.Builder addLogBuilder() {
        return getLogFieldBuilder().addBuilder(
            org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.getDefaultInstance());
      }
      public org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.Builder addLogBuilder(
          int index) {
        return getLogFieldBuilder().addBuilder(
            index, org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.getDefaultInstance());
      }
      public java.util.List<org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.Builder> 
           getLogBuilderList() {
        return getLogFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog, org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.Builder, org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogOrBuilder> 
          getLogFieldBuilder() {
        if (logBuilder_ == null) {
          logBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog, org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.Builder, org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogOrBuilder>(
                  log_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          log_ = null;
        }
        return logBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:RegionLogs)
    }
    
    static {
      defaultInstance = new RegionLogs(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RegionLogs)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RegionLog_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RegionLog_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RegionLogs_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RegionLogs_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/proto/BKWalFormats.proto\"-\n\tR" +
      "egionLog\022\016\n\006seqNum\030\001 \001(\003\022\020\n\010ledgerId\030\002 \001" +
      "(\003\"%\n\nRegionLogs\022\027\n\003log\030\001 \003(\0132\n.RegionLo" +
      "gB/\n+org.apache.hadoop.hbase.regionserve" +
      "r.wal.bkH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RegionLog_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RegionLog_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RegionLog_descriptor,
              new java.lang.String[] { "SeqNum", "LedgerId", },
              org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.class,
              org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLog.Builder.class);
          internal_static_RegionLogs_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RegionLogs_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RegionLogs_descriptor,
              new java.lang.String[] { "Log", },
              org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs.class,
              org.apache.hadoop.hbase.regionserver.wal.bk.BKWalFormats.RegionLogs.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
